### ISSUE TITLE
Upon compiling it is spamming me authentication errors

### ISSUE THREAD

**Issue by zhasky** [nhalstead/Simple-Discord-Bot#3]
I tried changing tokens, messing around in the discord dashboard, didn't get any wiser, it's giving me lovely cheesy messages while telling me its not being able to authenticate.

Any help?

Thanks alot.

**Comment by nhalstead** [comment]
Hi @zhasky, I've updated the readme to have better _Getting Started_ instructions.

Give it a look and see if it helps you.
Be sure to pull down the latest code and do `npm install`
